//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace poic_2408.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("poic_2408.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_COPY {
            get {
                return ResourceManager.GetString("BUTTON_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_OVERWRITE {
            get {
                return ResourceManager.GetString("BUTTON_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrtSc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_SCREENSHOT {
            get {
                return ResourceManager.GetString("BUTTON_SCREENSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrtScMatch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_SCREENSHOTMATCH {
            get {
                return ResourceManager.GetString("BUTTON_SCREENSHOTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始/停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTON_STARTSTOP {
            get {
                return ResourceManager.GetString("BUTTON_STARTSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FORMAT_KEYVALUE {
            get {
                return ResourceManager.GetString("FORMAT_KEYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FORMAT_RATE {
            get {
                return ResourceManager.GetString("FORMAT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像認識に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR1 {
            get {
                return ResourceManager.GetString("MESS_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー名を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR10 {
            get {
                return ResourceManager.GetString("MESS_ERROR10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビューアの表示か後処理でエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR11 {
            get {
                return ResourceManager.GetString("MESS_ERROR11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインを読み込めませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR12 {
            get {
                return ResourceManager.GetString("MESS_ERROR12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を読み込めませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR13 {
            get {
                return ResourceManager.GetString("MESS_ERROR13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一部画像の読み込みに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR14 {
            get {
                return ResourceManager.GetString("MESS_ERROR14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定の保存に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR15 {
            get {
                return ResourceManager.GetString("MESS_ERROR15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字認識に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR2 {
            get {
                return ResourceManager.GetString("MESS_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像認識後の処理を実行できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR3 {
            get {
                return ResourceManager.GetString("MESS_ERROR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像のキャプチャに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR4 {
            get {
                return ResourceManager.GetString("MESS_ERROR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像認識後の処理が正常に実装されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR5 {
            get {
                return ResourceManager.GetString("MESS_ERROR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像処理に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR6 {
            get {
                return ResourceManager.GetString("MESS_ERROR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を取得できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR7 {
            get {
                return ResourceManager.GetString("MESS_ERROR7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像がセットされていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR8 {
            get {
                return ResourceManager.GetString("MESS_ERROR8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインの設定を読み込めませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_ERROR9 {
            get {
                return ResourceManager.GetString("MESS_ERROR9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ名前のファイルが存在しています\n上書きしてもよろしいですか に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESS_FILESAVE {
            get {
                return ResourceManager.GetString("MESS_FILESAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_BOTTOM {
            get {
                return ResourceManager.GetString("STRING_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_CAPTURENO {
            get {
                return ResourceManager.GetString("STRING_CAPTURENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字認識 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_CHARACTERRECOGNITION {
            get {
                return ResourceManager.GetString("STRING_CHARACTERRECOGNITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_DEFAULT {
            get {
                return ResourceManager.GetString("STRING_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_FPS {
            get {
                return ResourceManager.GetString("STRING_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_HEIGHT {
            get {
                return ResourceManager.GetString("STRING_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_IMAGEPROCESSING {
            get {
                return ResourceManager.GetString("STRING_IMAGEPROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像認識 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_IMAGERECOGNITION {
            get {
                return ResourceManager.GetString("STRING_IMAGERECOGNITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_KEYNAME {
            get {
                return ResourceManager.GetString("STRING_KEYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_LEFT {
            get {
                return ResourceManager.GetString("STRING_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一致率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_MATCHRATE {
            get {
                return ResourceManager.GetString("STRING_MATCHRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   観測 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_OBSERVATION {
            get {
                return ResourceManager.GetString("STRING_OBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きの確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_OVERWRITECONF {
            get {
                return ResourceManager.GetString("STRING_OVERWRITECONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_REFPS {
            get {
                return ResourceManager.GetString("STRING_REFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_RIGHT {
            get {
                return ResourceManager.GetString("STRING_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_SETTINGS {
            get {
                return ResourceManager.GetString("STRING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_TOP {
            get {
                return ResourceManager.GetString("STRING_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面に表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_TOPMOST {
            get {
                return ResourceManager.GetString("STRING_TOPMOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   映像ソース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_VIDEOCAPTURE {
            get {
                return ResourceManager.GetString("STRING_VIDEOCAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビューア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_VIEWER {
            get {
                return ResourceManager.GetString("STRING_VIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_WIDTH {
            get {
                return ResourceManager.GetString("STRING_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_X {
            get {
                return ResourceManager.GetString("STRING_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STRING_Y {
            get {
                return ResourceManager.GetString("STRING_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   poic_2408 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_CODE {
            get {
                return ResourceManager.GetString("TOOL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   p-GART に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_NAME {
            get {
                return ResourceManager.GetString("TOOL_NAME", resourceCulture);
            }
        }
    }
}
